#pragma once

#ifdef RGBLIGHT_ENABLE
#    define RGBLIGHT_EFFECT_BREATHING
#endif

#define TAP_CODE_DELAY 5

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 2

#define COMBO_COUNT 17
#define COMBO_SHOULD_TRIGGER
#define LEADER_TIMEOUT 300

#define NO_USB_STARTUP_CHECK
#define USB_SUSPEND_WAKEUP_DELAY 500
