#pragma once

#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_SLEEP
    #define RGBLIGHT_LAYERS
    #define RGBLIGHT_SPLIT
    #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#endif

#define TAP_CODE_DELAY 5

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE

#define COMBO_COUNT 17
#define COMBO_SHOULD_TRIGGER
#define LEADER_TIMEOUT 300

#define USB_SUSPEND_WAKEUP_DELAY 500
